// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeUdXBmnoiSAxtbdpOKq4bE1DNPqhN9Q',
    appId: '1:87101874979:web:9422da60260adbdce5e296',
    messagingSenderId: '87101874979',
    projectId: 'cameleon-note',
    authDomain: 'cameleon-note.firebaseapp.com',
    storageBucket: 'cameleon-note.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-x3_OdJXN73eFRYw5gBMG7L7I3was938',
    appId: '1:87101874979:android:607b8aad25339cf8e5e296',
    messagingSenderId: '87101874979',
    projectId: 'cameleon-note',
    storageBucket: 'cameleon-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-Twl2r7UBGMUiNbAbRF28hQXmHAeJ4k',
    appId: '1:87101874979:ios:a0c130ee873c1a73e5e296',
    messagingSenderId: '87101874979',
    projectId: 'cameleon-note',
    storageBucket: 'cameleon-note.appspot.com',
    iosClientId: '87101874979-f8uer5bm21u9lnf76n30mdc78072otuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameleonNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-Twl2r7UBGMUiNbAbRF28hQXmHAeJ4k',
    appId: '1:87101874979:ios:a0c130ee873c1a73e5e296',
    messagingSenderId: '87101874979',
    projectId: 'cameleon-note',
    storageBucket: 'cameleon-note.appspot.com',
    iosClientId: '87101874979-f8uer5bm21u9lnf76n30mdc78072otuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameleonNote',
  );
}
